[package]
name = "test_progs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
env_logger = "0.11.6"
log = "0.4"
std-embedded-nal = "0.4"
embedded-nal = "0.9"
demos = { path = "../demos" }
