[target.'cfg(all(target_arch = "arm", target_os = "none"))']

runner = "probe-rs run --chip ATSAMD21G18A"

rustflags = [
  "-C", "linker=flip-link",
]

[build]
target = "thumbv6m-none-eabi"    # Cortex-M0 and Cortex-M0+

[alias]
rb = "run --example"
rrb = "run --release --example"
