name: Benchmarks

on:
    push:
      branches:
        - '*'
    pull_request:
      branches:
        - '*'


permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Rust benchmark example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain update nightly && rustup default nightly

      - name: Create benchmark results file
        run: |
          echo '[{"name": "custommetric", "unit": "kilobyte","value" : 20}]' > benchmark_results.json
          cat benchmark_results.json  # Debug: show what we created

      - name: Upload benchmark files
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-files
          path: benchmark_results.json
        if: always()  # This ensures it runs even if later steps fail

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: customSmallerIsBetter
          output-file-path: benchmark_results.json
